### PR TITLE
Removing "Something Else" (extra context)

### PR DESCRIPTION
**Pull request by noahwsmith**
This must have been a relic of testing, somewhere. Credit to @ajstanley for pointing this out
https://github.com/Islandora-Devops/isle-dc/pull/248#issuecomment-1100659447

### CODE REVIEW

**Comment by noahwsmith** [comment]
@ajstanley do you have bandwidth to test this? Danny says these three file deletions should do the trick.

Thanks!

**Comment by noahwsmith** [comment]
@ysuarez perhaps you could test this? Outcome is that the extra/bogus context should be gone.

**Comment by rosiel** [comment]
I think this should do it. Mind if I merge?

**Comment by noahwsmith** [comment]
yes please!

**Pull request merged**
